### ISSUE TITLE
Google Drive link used to download Celeb-A5 dataset no longer works

### ISSUE THREAD

**Issue by MyJumperBroke23** [seungjaeryanlee/pure-noise#26]
This link: https://drive.google.com/uc?id=1l3FoP44bd9U0xtq74OLKcF0JTF_XSecF

found in prepare_celeba5.py no longer works, would it be possible for you to upload your version, and replace the url?

**Comment by seungjaeryanlee** [comment]
Indeed, it seems like the CelebA-5 dataset link no longer works. I would suggest contacting the authors of [M2m](https://arxiv.org/abs/2004.00431) who originally proposed the CelebA-5 dataset for guidance, since I believe they used to provide it. Their source code can be found here: https://github.com/alinlab/M2m
